include:
  - my-apps.yml
  - services.yml

services:

  reverse-proxy:
    image: ${LSIO_REGISTRY}/swag
    container_name: reverse-proxy
    env_file: secrets/lets-encrypt.env
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${USER_ID}
      - PGID=${USER_ID}
      - TZ=${TIMEZONE}
      - VALIDATION=http
    volumes:
      - ./nginx:/config/nginx:Z
      - ./pages:/config/pages:Z
      - ${DATA_DIR}/nginx-logs:/config/log/nginx:Z
      - ${DATA_DIR}/fileserver:/config/fileserver:Z
    ports:
      - 443:443
      - 80:80
    restart: always

  unifi-app:
    image: ${LSIO_REGISTRY}/unifi-network-application
    container_name: unifi-app
    env_file: secrets/unifi.env
    depends_on:
      - unifi-db
    environment:
      - PUID=${USER_ID}
      - PGID=${USER_ID}
      - TZ=${TIMEZONE}
      - MONGO_USER=unifi
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    volumes:
      - ${DATA_DIR}/unifi:/config:Z
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
    restart: always

  unifi-db:
    image: docker.io/mongo:8.0
    container_name: unifi-db
    env_file: secrets/unifi.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_USER=unifi
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    volumes:
      - ${DB_DIR}/unifi:/data/db:Z
      - ${CONFIG_DIR}/unifi-db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:Z,ro
    restart: always

  cups:
    build: ./cups
    container_name: cups
    privileged: true
    volumes:
      - ${CONFIG_DIR}/cups:/etc/cups:Z
      - /var/run/dbus:/var/run/dbus:Z,ro
      - /dev/bus/usb/001:/dev/bus/usb/001:Z
    ports:
      - 631:631
    restart: always
