version: '3.6'

services:

  #
  # Domain Control
  #

  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /lakefront/config/ddclient:/config
    restart: unless-stopped

  reverse-proxy:
    image: linuxserver/letsencrypt
    container_name: reverse-proxy
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - FILE__URL=/run/secrets/DOMAIN
      - FILE__SUBDOMAINS=/run/secrets/SUBDOMAINS
      - VALIDATION=http
      - FILE__EMAIL=/run/secrets/EMAIL
      - DHLEVEL=2048
      - ONLY_SUBDOMAINS=false
      - FILE__EXTRA_DOMAINS=/run/secrets/EXTRA_DOMAINS
      - STAGING=false
    secrets:
      - EMAIL
      - DOMAIN
      - SUBDOMAINS
      - EXTRA_DOMAINS
    volumes:
      - ./proxy-confs:/config/nginx/proxy-confs
      - ./personal-site:/config/www
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  #
  # Nextcloud
  #

  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud-db
      - MYSQL_USER=nextcloud
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    volumes:
      - /lakefront/nextcloud/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - 3306:3306
    restart: unless-stopped

  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    links:
      - nextcloud-db
    volumes:
      - /lakefront/nextcloud/app:/var/www/html
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - 8080:80
    restart: unless-stopped

  #
  # Home Assistant (Core)
  #

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - /lakefront/config/mqtt:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped

  home-assistant:
    image: homeassistant/home-assistant
    container_name: home-assistant
    environment:
      - TZ=America/Chicago
    volumes:
      - /lakefront/config/home-assistant:/config
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    network_mode: host
#    ports:
#      - 8086:80
    restart: unless-stopped

  #
  # Plex
  #

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=public
      - UMASK_SET=022
      - FILE__PLEX_CLAIM=/run/secrets/PLEX_CLAIM
    secrets:
      - PLEX_CLAIM
    volumes:
      - /lakefront/config/plex:/config
      - /lakefront/movies:/movies
      - /lakefront/tv:/tv
      - /lakefront/music:/music
      - /lakefront/photos:/photos
      - /lakefront/mom/Pictures:/mom
      - /lakefront/videos:/videos
#    ports:
#      - 8087:80
    restart: unless-stopped

  #
  # LibreSpeed
  #

  speedtest:
    image: adolfintel/speedtest
    container_name: speedtest
    environment:
      - MODE=standalone
      - TELEMETRY=false
#    ports:
#      - 8084:80
    restart: unless-stopped

  #
  # NGINX Web Servers
  #

  otd-calcs-web:
    image: linuxserver/nginx
    container_name: otd-calcs-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./otd-calcs-web:/config/www
#    ports:
#      - 8081:80
    restart: unless-stopped

  homepage:
    image: linuxserver/nginx
    container_name: homepage
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./homepage:/config/www
#    ports:
#      - 8082:80
    restart: unless-stopped

  wildrank:
    image: python:3
    container_name: wildrank
    working_dir: /www
    command: python post-server.py
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./wildrank:/www
#    ports:
#      - 8086:80
    restart: unless-stopped

secrets:
  PLEX_CLAIM:
    file: ./secrets/plex_claim
  EMAIL:
    file: ./secrets/email
  DOMAIN:
    file: ./secrets/domain
  SUBDOMAINS:
    file: ./secrets/subdomains
  EXTRA_DOMAINS:
    file: ./secrets/extra_domains
  MYSQL_PASSWORD:
    file: ./secrets/mysql_password
  MYSQL_ROOT_PASSWORD:
    file: ./secrets/mysql_root_password