version: '2'

# TODO:
# Integrate linuxserver/ddclient
# Automate updates
# Status monitor

services:
  
  reverse-proxy:
    image: linuxserver/letsencrypt
    container_name: reverse-proxy
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - URL=[domain]
      - SUBDOMAINS=[subdomains],
      - VALIDATION=http
      - EMAIL=[email]
      - DHLEVEL=2048
      - ONLY_SUBDOMAINS=false
      - EXTRA_DOMAINS=[other domains]
      - STAGING=false
    volumes:
      - ./proxy-confs:/config/nginx/proxy-confs
      - ./personal-site:/config/www
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=[password]
      - MYSQL_PASSWORD=[password]
      - MYSQL_DATABASE=nextcloud-db
      - MYSQL_USER=nextcloud
    volumes:
      - /lakefront/nextcloud/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - 3306:3306
    restart: unless-stopped

  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    links:
      - nextcloud-db
    volumes:
      - /lakefront/nextcloud/app:/var/www/html
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - 8080:80
    restart: unless-stopped

  home-assistant:
    image: homeassistant/home-assistant:stable
    container_name: home-assistant
    environment:
      - TZ=America/Chicago
    volumes:
      - /lakefront/config/home-assistant:/config
    network_mode: host
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=public
      - UMASK_SET=022
      - PLEX_CLAIM=[claim code]
    volumes:
      - /lakefront/config/plex:/config
      - /lakefront/movies:/movies
      - /lakefront/tv:/tv
      - /lakefront/music:/music
      - /lakefront/photos:/photos
      - /lakefront/mom/Pictures:/mom
      - /lakefront/videos:/videos
    restart: unless-stopped

  otd-calcs-web:
    image: linuxserver/nginx
    container_name: otd-calcs-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./otd-calcs-web:/config/www
#    ports:
#      - 8081:80
    restart: unless-stopped

  homepage:
    image: linuxserver/nginx
    container_name: homepage
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./homepage:/config/www
#    ports:
#      - 8082:80
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - /lakefront/config/mqtt:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
