version: '3.6'

services:

  #
  # Networking
  #

  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /westside/config/ddclient:/config
    restart: unless-stopped

  reverse-proxy:
    image: linuxserver/letsencrypt
    container_name: reverse-proxy
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - FILE__URL=/run/secrets/DOMAIN
      - FILE__SUBDOMAINS=/run/secrets/SUBDOMAINS
      - VALIDATION=http
      - FILE__EMAIL=/run/secrets/EMAIL
      - DHLEVEL=2048
      - ONLY_SUBDOMAINS=false
      - FILE__EXTRA_DOMAINS=/run/secrets/EXTRA_DOMAINS
      - STAGING=false
    secrets:
      - EMAIL
      - DOMAIN
      - SUBDOMAINS
      - EXTRA_DOMAINS
    volumes:
      - ./proxy-confs:/config/nginx/proxy-confs
      - ./personal-site:/config/www
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  unifi:
    image: linuxserver/unifi-controller
    container_name: unifi
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /westside/config/unifi:/config
    restart: unless-stopped

#  wireguard:
#    image: linuxserver/wireguard
#    container_name: wireguard
#    cap_add:
#      - NET_ADMIN
#      - SYS_MODULE
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=America/Chicago
#      - SERVERURL=apt.fruzyna.net
#      - SERVERPORT=51820
#      - PEERS=5
#      - INTERNAL_SUBNET=192.168.69.0
#    volumes:
#      - /westside/config/wireguard:/config
#      - /lib/modules:/lib/modules
#    ports:
#      - 51820:51820/udp
#    sysctls:
#      - net.ipv4.conf.all.src_valid_mark=1
#    restart: unless-stopped

  #
  # Services 
  #

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - finance-db
    ports:
      - 8083:8080
    restart: unless-stopped

  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - PASSWORD=[password]
      - SUDO_PASSWORD=[password]
    secrets:
      - CODE_PASSWORD
    volumes:
      - /westside/config:/configs
      - /dropbox:/dropbox
    restart: unless-stopped

  finance-app:
    image: node
    container_name: finance-app
    working_dir: /app
    command: ./install-and-start.sh
    depends_on:
      - finance-db
    volumes:
      - ./finance-v2:/app
    restart: unless-stopped

  finance-db:
    image: mariadb
    container_name: finance-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
      - MYSQL_DATABASE=finance-db
      - MYSQL_USER=finance
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    volumes:
      - /westside/config/finance/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3306:3306
    restart: unless-stopped

  gitea-app:
    image: gitea/gitea
    container_name: gitea-app
    depends_on:
      - gitea-db
    volumes:
      - /westside/config/gitea:/data
    ports:
      - 2222:0022
    restart: unless-stopped

  gitea-db:
    image: mariadb
    container_name: gitea-db
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
      - MYSQL_DATABASE=gitea-db
      - MYSQL_USER=gitea
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    volumes:
      - /westside/databases/gitea:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  home-assistant:
    image: homeassistant/home-assistant
    container_name: home-assistant
    depends_on:
      - mqtt
    environment:
      - TZ=America/Chicago
    volumes:
      - /westside/config/home-assistant:/config
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    network_mode: host
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - /westside/config/mqtt:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped

  netbootxyz:
    image: linuxserver/netbootxyz
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /westside/config/pxe:/config
      - /westside/images:/assets
    ports:
      - 8081:3000
      - 69:69/udp
      - 8082:80
    restart: unless-stopped

  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    depends_on:
      - nextcloud-db
    volumes:
      - /westside/config/nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud-db
      - MYSQL_USER=nextcloud
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    volumes:
      - /westside/databases/nextcloud:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=public
      - UMASK_SET=022
      - FILE__PLEX_CLAIM=/run/secrets/PLEX_CLAIM
    secrets:
      - PLEX_CLAIM
    volumes:
      - /westside/config/plex:/config
      - /westside/media/movies:/movies
      - /westside/media/tv:/tv
      - /westside/media/music:/music
      - /westside/media/videos:/videos
      - /westside/mom/Megan Pictures:/mom:ro
    restart: unless-stopped

  speedtest:
    image: adolfintel/speedtest
    container_name: speedtest
    environment:
      - MODE=standalone
      - TELEMETRY=false
    # port held open for internal network testing
    ports:
      - 8888:80
    restart: unless-stopped

  statping:
    image: statping/statping
    container_name: statping
    environment:
      DB_CONN: sqlite
    volumes:
      - /westside/config/statping:/app
    restart: unless-stopped

  telegram:
    image: mail929/telegram-react
    container_name: telegram
    environment:
      - REACT_APP_TELEGRAM_API_ID_FILE=/run/secrets/TELEGRAM_API_ID
      - REACT_APP_TELEGRAM_API_HASH_FILE=/run/secrets/TELEGRAM_API_HASH
    secrets:
      - TELEGRAM_API_ID
      - TELEGRAM_API_HASH
    restart: unless-stopped

  wiki:
    image: linuxserver/wikijs
    container_name: wiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /westside/config/wiki:/config
      - /westside/databases/wiki:/data
    restart: unless-stopped

  #
  # NGINX Web Servers
  #

  climate:
    image: linuxserver/nginx
    container_name: climate
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./climatechangeisreal:/config/www
    restart: unless-stopped

  homepage:
    image: linuxserver/nginx
    container_name: homepage
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./homepage:/config/www
    restart: unless-stopped

  otd-calcs-web:
    image: linuxserver/nginx
    container_name: otd-calcs-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./otd-calcs-web:/config/www
    restart: unless-stopped

  wildrank:
    image: python:3
    container_name: wildrank
    working_dir: /www
    command: python python/post-server.py
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./wildrank:/www
    restart: unless-stopped

  #
  # Games
  #

#  minecraft:
#    image: itzg/minecraft-server
#    container_name: minecraft
#    environment:
#      - EULA=TRUE
#    volumes:
#      - /westside/config/minecraft:/data
#    ports:
#      - 25565:25565
#    restart: unless-stopped

secrets:
  PLEX_CLAIM:
    file: ./secrets/plex_claim
  EMAIL:
    file: ./secrets/email
  DOMAIN:
    file: ./secrets/domain
  SUBDOMAINS:
    file: ./secrets/subdomains
  EXTRA_DOMAINS:
    file: ./secrets/extra_domains
  MYSQL_PASSWORD:
    file: ./secrets/mysql_password
  MYSQL_ROOT_PASSWORD:
    file: ./secrets/mysql_root_password
  CODE_PASSWORD:
    file: ./secrets/code_password
  TELEGRAM_API_ID:
    file: ./secrets/telegram_api_id
  TELEGRAM_API_HASH:
    file: ./secrets/telegram_api_hash
