version: '3.7'

services:

  #
  # Networking
  #

  ddclient:
    image: ghcr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /westside/config/ddclient:/config
    restart: unless-stopped

  reverse-proxy:
    image: ghcr.io/linuxserver/swag:latest
    container_name: reverse-proxy
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - FILE__URL=/run/secrets/DOMAIN
      - FILE__SUBDOMAINS=/run/secrets/SUBDOMAINS
      - VALIDATION=http
      - FILE__EMAIL=/run/secrets/EMAIL
      - DHLEVEL=2048
      - ONLY_SUBDOMAINS=false
      - FILE__EXTRA_DOMAINS=/run/secrets/EXTRA_DOMAINS
      - STAGING=false
    secrets:
      - EMAIL
      - DOMAIN
      - SUBDOMAINS
      - EXTRA_DOMAINS
    volumes:
      - ./nginx:/config/nginx
      - ./personal-site:/config/www
      - ./otd-calcs-web:/config/otd
      - ./homepage:/config/home
      - ./robot_framework/docs:/config/robot_docs
      - ./ws-links:/config/ws-links
      - ./links:/config/links
      - ./status-page:/config/status
      - ./billy:/config/billy
      - /westside/databases/fileserver:/config/fileserver
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  unifi:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /westside/config/unifi:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
    restart: unless-stopped

  #
  # Services 
  #

  #adminer:
  #  image: adminer
  #  container_name: adminer
  #  depends_on:
  #    - finance-db
  #  ports:
  #    - 8099:8080
  #  restart: unless-stopped

  baikal:
    image: ckulka/baikal:nginx
    container_name: baikal
    volumes:
      - /westside/config/baikal:/var/www/baikal/config
      - /westside/databases/baikal:/var/www/baikal/Specific
    ports:
      - 8085:80
    restart: unless-stopped

  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /westside/config/emulatorjs:/config
      - /westside/databases/emulatorjs:/data
    ports:
      - 8091:80
      - 8092:3000
    restart: unless-stopped

  finance-app:
    image: node
    container_name: finance-app
    working_dir: /app
    command: ./install-and-start.sh
    depends_on:
      - finance-db
    volumes:
      - ./finance-v2:/app
    ports:
      - 8086:3000
    restart: unless-stopped

  finance-db:
    image: mariadb
    container_name: finance-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
      - MYSQL_DATABASE=finance-db
      - MYSQL_USER=finance
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    volumes:
      - /westside/config/finance/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3306:3306
    restart: unless-stopped

  gitea-app:
    image: gitea/gitea
    container_name: gitea-app
    depends_on:
      - gitea-db
    volumes:
      - /westside/config/gitea:/data
    ports:
      - 2222:0022
      - 8087:3000
    restart: unless-stopped

  gitea-db:
    image: mariadb
    container_name: gitea-db
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
      - MYSQL_DATABASE=gitea-db
      - MYSQL_USER=gitea
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    volumes:
      - /westside/databases/gitea:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    container_name: home-assistant
    depends_on:
      - mqtt
    environment:
      - TZ=America/Chicago
    volumes:
      - /westside/config/home-assistant:/config
      - /westside/media:/media
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    network_mode: host
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    environment:
      - JELLYFIN_PublishedServerUrl=http://192.168.16.11:8096
    volumes:
      - /westside/config/jellyfin:/config
      - /westside/databases/jellyfin:/cache
      - /westside/media/music:/media/music
      - /westside/media/movies:/media/movies
      - /westside/media/tv:/media/tv
    ports:
      - 8096:8096
      - 7359:7359/udp
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - /westside/config/mqtt:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped

  miniflux-app:
    image: miniflux/miniflux
    container_name: miniflux-app
    depends_on:
      - miniflux-db
    environment:
      - DATABASE_URL=
      - RUN_MIGRATIONS=1
    ports:
      - 8090:8080
    restart: unless-stopped

  miniflux-db:
    image: postgres:15
    container_name: miniflux-db
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    volumes:
      - /westside/databases/miniflux:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

  photoprism:
    image: photoprism/photoprism
    container_name: photoprism
    user: "1000:1000"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: ""
      PHOTOPRISM_SITE_URL: "http://photos.fruzyna.net/"
      PHOTOPRISM_SITE_AUTHOR: "Liam Fruzyna"
      PHOTOPRISM_SITE_TITLE: "Liam's Photos"
      PHOTOPRISM_SITE_CAPTION: ""
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_HTTP_HOST: "0.0.0.0"
      PHOTOPRISM_JPEG_QUALITY: 92
      PHOTOPRISM_DISABLE_CHOWN: "true"
    volumes:
      - /westside/config/photoprism:/photoprism/storage
      - /westside/media/pictures:/photoprism/originals
      - /photo-import:/photoprism/import
    ports:
      - 8084:2342
    restart: unless-stopped

  wiki:
    image: ghcr.io/linuxserver/wikijs
    container_name: wiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /westside/config/wiki:/config
      - /westside/databases/wiki:/data
    ports:
      - 8088:3000
    restart: unless-stopped

  wildrank-dev:
    image: ghcr.io/wildstang/wildrank:2.3.1
    container_name: wildrank-dev
    environment:
      - WR_WORKERS=1
      - PASSWORD=liamstestserver
    volumes:
      - /westside/config/wildrank-dev:/config
      - /westside/databases/wildrank-dev:/uploads
    ports:
      - 8083:80
    restart: unless-stopped

  wildrank-test:
    image: ghcr.io/wildstang/wildrank:2.3.1
    container_name: wildrank-test
    environment:
      - WR_WORKERS=5
      - PASSWORD=testserver
    volumes:
      - /westside/config/wildrank-test:/config
      - /westside/databases/wildrank-test:/uploads
    ports:
      - 8082:80
    restart: unless-stopped

  wildrank:
    image: ghcr.io/wildstang/wildrank:2.3.1
    container_name: wildrank
    environment:
      - WR_WORKERS=10
      - PASSWORD=deytookerclers
    volumes:
      - /westside/config/wildrank:/config
      - /westside/databases/wildrank:/uploads
    ports:
      - 8081:80
    restart: unless-stopped

  #
  # Games
  #

  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    environment:
      - EULA=TRUE
    volumes:
      - /westside/config/minecraft:/data
    ports:
      - 25565:25565
    restart: unless-stopped

secrets:
  EMAIL:
    file: ./secrets/email
  DOMAIN:
    file: ./secrets/domain
  SUBDOMAINS:
    file: ./secrets/subdomains
  EXTRA_DOMAINS:
    file: ./secrets/extra_domains
  MYSQL_PASSWORD:
    file: ./secrets/mysql_password
  MYSQL_ROOT_PASSWORD:
    file: ./secrets/mysql_root_password
