version: '2'

volumes:
  reverse-proxy:
  nextcloud-db:
  nextcloud-app:
  mc-spigot:
  finance:

services:
  # NGINX reverse proxy to make some stuff accessible to the outside world
  reverse-proxy:
    image: linuxserver/letsencrypt
    container_name: reverse-proxy
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - URL=mail929.com
      - SUBDOMAINS=cloud,otd,
      - VALIDATION=http
      - EMAIL=liamfruzyna@gmail.com
      - DHLEVEL=2048
      - ONLY_SUBDOMAINS=false
      - EXTRA_DOMAINS=
      - STAGING=false
    volumes:
      - reverse-proxy:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  # MariaDB database for Nextcloud
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=[db-root-pw]
      - MYSQL_PASSWORD=[db-user-pw]
      - MYSQL_DATABASE=nextcloud-db
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  # personal Nextcloud instance
  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    links:
      - nextcloud-db
    volumes:
      - nextcloud-app:/var/www/html
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - 8082:80
    restart: unless-stopped

  # Spigot Minecraft Server that I may use one day
  mc-spigot:
    image: itzg/minecraft-server
    container_name: mc-spigot
    environment:
      EULA: "true"
      TYPE: SPIGOT
      VERSION: 1.14.4
      OPS: Mail929
      SERVER_NAME: MAIL-SPIGOT
      MOTD: Stay away...
    command: --noconsole
    ports:
      - 25565:25565
    volumes:
      - mc-spigot:/data
    restart: unless-stopped

  # my personal finances webapp
  finance:
    build: finance
    container_name: finance
    ports:
      - 8080:8080
    volumes:
      - finance:/root/.config/finance
    restart: unless-stopped

  # NGINX web server to run my OTD Calculator website @ otd.mail929.com
  otd-calcs-web:
    build: otd
    container_name: otd-calcs-web
#    ports:
#      - 8081:80
    restart: unless-stopped

  # web redirect from mail929.com to mail929.github.io
  redirect:
    image: morbz/docker-web-redirect
    container_name: redirect
    environment:
      - REDIRECT_TARGET=mail929.github.io
    restart: unless-stopped
