version: '2'

# docker volumes in /var/lib/docker/volumes
volumes:
  nextcloud-db:
  nextcloud-app:
  home-assistant:
  plex:
#  mc-spigot:

# TODO:
# Verify new nextcloud setup works
# Integrate linuxserver/ddclient
# Move plex data to external drive
# Automate updates
# Status monitor

services:
  # reverse proxy with let's encrypt to allow outside access with only standard ports
  reverse-proxy:
    image: linuxserver/letsencrypt
    container_name: reverse-proxy
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - URL=[domain]
      - SUBDOMAINS=[subdomains],
      - VALIDATION=http
      - EMAIL=[email]
      - DHLEVEL=2048
      - ONLY_SUBDOMAINS=false
      - EXTRA_DOMAINS=[other domains]
      - STAGING=false
    volumes:
      - ./proxy-confs:/config/nginx/proxy-confs
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=[password]
      - MYSQL_PASSWORD=[password]
      - MYSQL_DATABASE=nextcloud-db
      - MYSQL_USER=nextcloud
    volumes:
      - nextcloud-db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - 3306:3306
    restart: unless-stopped

  nextcloud-app:
    image: nextcloud
    container_name: nextcloud-app
    links:
      - nextcloud-db
    volumes:
      - nextcloud-app:/var/www/html
      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - 8080:80
    restart: unless-stopped

  home-assistant:
    image: homeassistant/home-assistant:stable
    container_name: home-assistant
    environment:
      - TZ=America/Chicago
    volumes:
      - home-assistant:/config
    network_mode: host
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=public
      - UMASK_SET=022
#      - PLEX_CLAIM=[claim code]
    volumes:
      - plex:/config
      - /home/mail929/movies:/movies
      - /home/mail929/tv:/tv
      - /home/mail929/music:/music
      - /home/mail929/photos:/photos
      - /home/mail929/videos:/videos
    restart: unless-stopped

  otd-calcs-web:
    image: linuxserver/nginx
    container_name: otd-calcs-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./otd-calcs-web:/config/www
#    ports:
#      - 8081:80
    restart: unless-stopped

  homepage:
    image: linuxserver/nginx
    container_name: homepage
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./homepage:/config/www
#    ports:
#      - 8082:80
    restart: unless-stopped

  personal-site:
    image: linuxserver/nginx
    container_name: personal-site
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - ./personal-site:/config/www
#    ports:
#      - 8083:80
    restart: unless-stopped

#  mc-spigot:
#    image: itzg/minecraft-server
#    container_name: mc-spigot
#    environment:
#      EULA: "true"
#      TYPE: SPIGOT
#      VERSION: 1.14.4
#      OPS: Mail929
#      SERVER_NAME: MAIL-SPIGOT
#      MOTD: Stay away...
#    command: --noconsole
#    ports:
#      - 25565:25565
#    volumes:
#      - mc-spigot:/data
#    restart: unless-stopped
