version: '3.7'

services:

  #
  # Networking
  #

  ddclient:
    image: linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /westside/config/ddclient:/config
    restart: unless-stopped

  reverse-proxy:
    image: linuxserver/swag
    container_name: reverse-proxy
    network_mode: host
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - FILE__URL=/run/secrets/DOMAIN
      - FILE__SUBDOMAINS=/run/secrets/SUBDOMAINS
      - VALIDATION=http
      - FILE__EMAIL=/run/secrets/EMAIL
      - DHLEVEL=2048
      - ONLY_SUBDOMAINS=false
      - FILE__EXTRA_DOMAINS=/run/secrets/EXTRA_DOMAINS
      - STAGING=false
    secrets:
      - EMAIL
      - DOMAIN
      - SUBDOMAINS
      - EXTRA_DOMAINS
    volumes:
      - ./proxy-confs:/config/nginx/proxy-confs
      - ./site-confs:/config/nginx/site-confs
      - ./personal-site:/config/www
      - ./otd-calcs-web:/config/otd
      - ./homepage:/config/home
      - ./rip:/config/rip
      - ./robot_framework/docs:/config/robot_docs
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  unifi:
    image: linuxserver/unifi-controller
    container_name: unifi
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /westside/config/unifi:/config
    restart: unless-stopped

  #
  # Services 
  #

  #adminer:
  #  image: adminer
  #  container_name: adminer
  #  depends_on:
  #    - finance-db
  #  ports:
  #    - 8083:8080
  #  restart: unless-stopped

  baikal:
    image: ckulka/baikal:nginx
    container_name: baikal
    volumes:
      - /westside/config/baikal:/var/www/baikal/config
      - /westside/databases/baikal:/var/www/baikal/Specific
    ports:
      - 8085:80
    restart: unless-stopped

  finance-app:
    image: node
    container_name: finance-app
    working_dir: /app
    command: ./install-and-start.sh
    depends_on:
      - finance-db
    volumes:
      - ./finance-v2:/app
    ports:
      - 8086:3000
    restart: unless-stopped

  finance-db:
    image: mariadb
    container_name: finance-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
      - MYSQL_DATABASE=finance-db
      - MYSQL_USER=finance
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    volumes:
      - /westside/databases/finance:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3306:3306
    restart: unless-stopped

  gitea-app:
    image: gitea/gitea
    container_name: gitea-app
    depends_on:
      - gitea-db
    volumes:
      - /westside/config/gitea:/data
    ports:
      - 2222:0022
      - 8087:3000
    restart: unless-stopped

  gitea-db:
    image: mariadb
    container_name: gitea-db
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD_FILE=/run/secrets/MYSQL_PASSWORD
      - MYSQL_DATABASE=gitea-db
      - MYSQL_USER=gitea
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    volumes:
      - /westside/databases/gitea:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  home-assistant:
    image: homeassistant/home-assistant
    container_name: home-assistant
    depends_on:
      - mqtt
    environment:
      - TZ=America/Chicago
    volumes:
      - /westside/config/home-assistant:/config
      - /westside/media:/media
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    network_mode: host
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - /westside/config/mqtt:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped

  #netbootxyz:
  #  image: linuxserver/netbootxyz
  #  container_name: netbootxyz
  #  environment:
  #    - PUID=1000
  #    - PGID=1000
  #    - TZ=America/Chicago
  #  volumes:
  #    - /westside/config/pxe:/config
  #    - /westside/images:/assets
  #  ports:
  #    - 8081:3000
  #    - 69:69/udp
  #    - 8082:80
  #  restart: unless-stopped
  
  photoprism:
    image: photoprism/photoprism
    container_name: photoprism
    user: "1000:1000"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: ""
      PHOTOPRISM_DEBUG: "false"
      PHOTOPRISM_PUBLIC: "false"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_SITE_URL: "http://photos.fruzyna.net/"
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: "Liam Fruzyna"
      PHOTOPRISM_HTTP_HOST: "0.0.0.0"
      PHOTOPRISM_HTTP_PORT: 2342
      PHOTOPRISM_SETTINGS_HIDDEN: "false"
      PHOTOPRISM_DATABASE_DRIVER: "sqlite"
      PHOTOPRISM_SIDECAR_JSON: "true"
      PHOTOPRISM_SIDECAR_YAML: "true"
      PHOTOPRISM_THUMB_FILTER: "lanczos"
      PHOTOPRISM_THUMB_UNCACHED: "false"
      PHOTOPRISM_THUMB_SIZE: 2048
      PHOTOPRISM_THUMB_SIZE_UNCACHED: 7680
      PHOTOPRISM_JPEG_SIZE: 7680
      PHOTOPRISM_JPEG_QUALITY: 92
      PHOTOPRISM_DARKTABLE_PRESETS: "false"
      UID: 1000
      GID: 1000
      UMASK: 0000
    volumes:
      - /westside/config/photoprism:/photoprism/storage
      - /westside/media/pictures:/photoprism/originals
    ports:
      - 8091:2342
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=public
      - UMASK_SET=022
      - FILE__PLEX_CLAIM=/run/secrets/PLEX_CLAIM
    secrets:
      - PLEX_CLAIM
    volumes:
      - /westside/config/plex:/config
      - /westside/media/movies:/movies
      - /westside/media/tv:/tv
      - /westside/media/music:/music
      - /westside/media/videos:/videos
      - /westside/mom/Megan Pictures:/mom:ro
    restart: unless-stopped

  speedtest:
    image: adolfintel/speedtest
    container_name: speedtest
    environment:
      - MODE=standalone
      - TELEMETRY=false
    ports:
      - 8888:80
    restart: unless-stopped

  wiki:
    image: linuxserver/wikijs
    container_name: wiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /westside/config/wiki:/config
      - /westside/databases/wiki:/data
    ports:
      - 8093:3000
    restart: unless-stopped

  wildrank:
    image: mail929/liamrank
    container_name: wildrank
    environment:
      - TBA_KEY=
    volumes:
      - /westside/config/wildrank:/config
      - /westside/databases/wildrank:/uploads
    ports:
      - 8094:80
    restart: unless-stopped

  #
  # Games
  #

  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    environment:
      - EULA=TRUE
    volumes:
      - /westside/config/minecraft:/data
    ports:
      - 25565:25565
    restart: unless-stopped

secrets:
  PLEX_CLAIM:
    file: ./secrets/plex_claim
  EMAIL:
    file: ./secrets/email
  DOMAIN:
    file: ./secrets/domain
  SUBDOMAINS:
    file: ./secrets/subdomains
  EXTRA_DOMAINS:
    file: ./secrets/extra_domains
  MYSQL_PASSWORD:
    file: ./secrets/mysql_password
  MYSQL_ROOT_PASSWORD:
    file: ./secrets/mysql_root_password
