services:

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    container_name: home-assistant
    depends_on:
      - mqtt
    environment:
      - TZ=America/Chicago
    volumes:
      - /wrigley/data/home-assistant:/config
      - /wrigley/config/home-assistant-ssh:/root/.ssh
    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_813005BC-if01-port0:/dev/ttyUSB1
    network_mode: host
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - /wrigley/config/mqtt:/mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped

  music-assistant:
    image: ghcr.io/music-assistant/server
    container_name: music-assistant
    volumes:
      - /wrigley/config/music-assistant:/data
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    security_opt:
      - apparmor:unconfined
    network_mode: host
    restart: unless-stopped

  piper:
    image: lscr.io/linuxserver/piper
    container_name: piper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/Chicago
      - PIPER_VOICE=en_US-lessac-medium
    volumes:
      - /wrigley/data/piper:/config
    ports:
      - 10200:10200
    restart: unless-stopped

  whisper:
    image: lscr.io/linuxserver/faster-whisper:gpu-version-v2.3.0
    container_name: whisper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/Chicago
      - WHISPER_MODEL=medium-int8
      - WHISPER_BEAM=5
    volumes:
      - /wrigley/data/whisper:/config
    ports:
      - 10300:10300
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

  #zones:
  #  image: everythingsmarthome/everything-presence-mmwave-configurator
  #  container_name: zones
  #  environment:
  #    - HA_URL=https://hass.fruzyna.net
  #    - HA_TOKEN=
  #  ports:
  #    - 8099:8099
  #  restart: unless-stopped
