services:

  finance-app:
    build: ./finance-v2
    container_name: finance-app
    command: ./install-and-start.sh
    depends_on:
      - finance-db
    volumes:
      - ./finance-v2:/app:Z
    ports:
      - ${FINANCE_PORT}:3000
    restart: always

  finance-db:
    image: docker.io/mariadb
    container_name: finance-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file: secrets/finance.env
    environment:
      - MYSQL_DATABASE=finance-db
      - MYSQL_USER=finance
    volumes:
      - ${DB_DIR}/finance:/var/lib/mysql:Z
      - /etc/localtime:/etc/localtime:ro
    restart: always

  metra:
    image: ${MY_REGISTRY}/metra
    container_name: metra
    volumes:
      - ${CONFIG_DIR}/metra:/config:Z
    ports:
      - ${METRA_PORT}:80
    restart: always

  personal-site:
    image: ${MY_REGISTRY}/site
    container_name: personal-site
    volumes:
      - ${CONFIG_DIR}/personal-site/pages:/app/pages:Z
      - ${CONFIG_DIR}/personal-site/assets:/app/assets:Z
    ports:
      - ${PERSONAL_PORT}:8000
    restart: always

  races:
    image: ${MY_REGISTRY}/races
    container_name: races
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${RACES_PORT}:8000
    restart: always

  wildrank:
    image: ${WS_REGISTRY}/wildrank:4.1.4
    container_name: wildrank
    env_file: secrets/wildrank.env
    environment:
      - WR_WORKERS=15
    volumes:
      - ${CONFIG_DIR}/wildrank:/config:Z
    ports:
      - ${WILDRANK_PORT}:80
    restart: always

  wildrank-test:
    image: ${WS_REGISTRY}/wildrank:4.1.4
    container_name: wildrank-test
    env_file: secrets/wildrank.env
    environment:
      - WR_WORKERS=5
    volumes:
      - ${CONFIG_DIR}/wildrank-test:/config:Z
    ports:
      - ${WILDRANK_TEST_PORT}:80
    restart: always

  wildrank-dev:
    image: ${WS_REGISTRY}/wildrank:250725-r2oc
    container_name: wildrank-dev
    env_file: secrets/wildrank.env
    environment:
      - WR_WORKERS=1
    volumes:
      - ${CONFIG_DIR}/wildrank-dev:/config:Z
    ports:
      - ${WILDRANK_DEV_PORT}:80
    restart: always

